name: yearly-report

on:
  schedule:
    - cron: "0 0 1 11 *" # runs at 00:00 UTC on first of November
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # install the python needed
      - name: pip install requirements
        run: |
          pip install -r requirements.txt --use-pep517
      - name: run python report.py
        run: |
          python report.py
      - name: commit report(s)
        run: |
          git config --global user.name 'Yossi'
          git config --global user.email 'yossi@users.noreply.github.com'
          git add .
          git commit -am "Automated davening report"
          git push
